#!/usr/bin/env python
"""results/summary -> paper/tables/*.tex and paper/numbers.tex. No number in the paper is typed
by hand: main.tex \\input{}s these, and any \\NUM{} key still undefined renders in red.

    python scripts/51_tables.py [--level 3]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from cueconf.config import PROJECT_ROOT, RESULTS_DIR, load_config  # noqa: E402

PAPER = PROJECT_ROOT / "paper"
PRETTY = {"llama32-3b": "Llama-3.2-3B", "llama32-3b-it": "Llama-3.2-3B-Inst.", "llama31-8b": "Llama-3.1-8B",
          "llama31-8b-it": "Llama-3.1-8B-Inst.", "gemma3-4b": "Gemma-3-4B", "olmo2-7b-it": "OLMo-2-7B-Inst.",
          "olmo3-7b-think": "OLMo-3-7B-Think"}


def pct(ci):
    if ci is None:
        return "--"
    p, lo, hi = ci
    return f"{100*p:.1f} {{\\scriptsize[{100*lo:.1f}, {100*hi:.1f}]}}"


def main() -> int:
    ap = argparse.ArgumentParser(); ap.add_argument("--level", type=int, default=3); a = ap.parse_args()
    numbers = {}
    for k in load_config("models.yaml")["models"]:
        for regime in ("cot", "direct"):
            f = RESULTS_DIR / "summary" / k / f"L{a.level}" / regime / "behavior_table.json"
            if not f.exists():
                continue
            t = json.loads(f.read_text())
            for target in ("v2", "v1"):
                inc = t.get(f"incongruent@{target}"); cong = t.get(f"congruent@{target}"); neu = t.get("neutral")
                if not inc:
                    continue
                tag = f"{k.replace('-', '')}{regime}{target}"
                numbers[f"interference{tag}"] = f"{100*t[f'interference@{target}'][0]:.1f}"
                numbers[f"lurerate{tag}"] = f"{100*inc['lure_rate'][0]:.1f}"
    # amendment 2: pooled contrasts across demonstration seeds, when the sweep exists
    sweep = RESULTS_DIR / "summary" / f"seed_sweep_L{a.level}.json"
    if sweep.exists():
        sw = json.loads(sweep.read_text())
        for key, rec in sw.items():
            k, regime = key.split("/")
            tag = f"{k.replace('-', '')}{regime}"
            for name, c in rec["contrasts"].items():
                cname, target = name.split("@")
                numbers[f"{cname}{tag}{target}"] = f"{100*c['pooled_mean']:+.1f}"
                numbers[f"{cname}{tag}{target}lo"] = f"{100*c['ci95'][0]:+.1f}"
                numbers[f"{cname}{tag}{target}hi"] = f"{100*c['ci95'][1]:+.1f}"
            for g, v in rec["groups"].items():
                numbers[f"acc{tag}{g.replace('@', '')}"] = f"{100*v['acc_mean']:.1f}"
                numbers[f"acc{tag}{g.replace('@', '')}lo"] = f"{100*v['acc_range'][0]:.1f}"
                numbers[f"acc{tag}{g.replace('@', '')}hi"] = f"{100*v['acc_range'][1]:.1f}"
            numbers[f"nseeds{tag}"] = str(len(rec["seeds"]))
    (PAPER / "tables").mkdir(exist_ok=True)
    # ---- Table 1: one row per (model, level, regime), pooled over demonstration seeds
    rows = []
    for L in (2, 3, 4, 5):
        sp = RESULTS_DIR / "summary" / f"seed_sweep_L{L}.json"
        if not sp.exists():
            continue
        sw = json.loads(sp.read_text())
        for key, rec in sw.items():
            k, regime = key.split("/")
            g = rec["groups"]
            def acc(name):
                return f"{100*g[name]['acc_mean']:.1f}" if name in g else "--"
            def rng(name):
                return f"{{\\scriptsize[{100*g[name]['acc_range'][0]:.0f},{100*g[name]['acc_range'][1]:.0f}]}}" if name in g else ""
            def con(name):
                c = rec["contrasts"].get(name)
                if not c:
                    return "--"
                star = "$^{*}$" if c["claimable"] else ""
                return f"{100*c['pooled_mean']:+.1f}{star}"
            rows.append((PRETTY.get(k, k), L, "CoT" if regime == "cot" else "direct", len(rec["seeds"]),
                         acc("neutral") + " " + rng("neutral"), acc("letter"),
                         con("facilitation@v1"), con("interference@v1"), con("lure_excess@v1"),
                         con("facilitation@v2"), con("interference@v2"), con("lure_excess@v2")))
    with (PAPER / "tables" / "behavior.tex").open("w") as f:
        f.write("\\begin{tabular}{llccllrrrrrr}\n\\toprule\n")
        f.write("Model & L & Regime & $S$ & Neutral & Letter & \\multicolumn{3}{c}{queried variable} & \\multicolumn{3}{c}{intermediate} \\\\\n")
        f.write("\\cmidrule(lr){7-9}\\cmidrule(lr){10-12}\n & & & & & & Facil. & Interf. & Lure$-$base & Facil. & Interf. & Lure$-$base \\\\\n\\midrule\n")
        for r in rows:
            f.write(" & ".join(str(x) for x in r) + " \\\\\n")
        f.write("\\bottomrule\n\\end{tabular}\n")
    print(f"Table 1: {len(rows)} rows over {len({r[1] for r in rows})} levels")
    with (PAPER / "numbers.tex").open("w") as f:
        f.write("% generated by scripts/51_tables.py -- do not edit\n")
        for key, val in sorted(numbers.items()):
            f.write(f"\\expandafter\\newcommand\\csname NUMval@{key}\\endcsname{{{val}}}\n")
        f.write("\\renewcommand{\\NUM}[1]{\\ifcsname NUMval@#1\\endcsname\\csname NUMval@#1\\endcsname\\else\\textcolor{red}{$\\langle\\langle$\\texttt{#1}$\\rangle\\rangle$}\\fi}\n")
    print(f"wrote {len(rows)} table rows, {len(numbers)} numbers")
    return 0


if __name__ == "__main__":
    sys.exit(main())
