#!/usr/bin/env python
"""results/summary -> paper/tables/*.tex and paper/numbers.tex. No number in the paper is typed
by hand: main.tex \\input{}s these, and any \\NUM{} key still undefined renders in red.

    python scripts/51_tables.py [--level 3]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from cueconf.config import PROJECT_ROOT, RESULTS_DIR, load_config  # noqa: E402

PAPER = PROJECT_ROOT / "paper"
PRETTY = {"llama32-3b": "Llama-3.2-3B", "llama32-3b-it": "Llama-3.2-3B-Inst.", "llama31-8b": "Llama-3.1-8B",
          "llama31-8b-it": "Llama-3.1-8B-Inst.", "gemma3-4b": "Gemma-3-4B", "olmo2-7b-it": "OLMo-2-7B-Inst.",
          "olmo3-7b-think": "OLMo-3-7B-Think"}


def pct(ci):
    if ci is None:
        return "--"
    p, lo, hi = ci
    return f"{100*p:.1f} {{\\scriptsize[{100*lo:.1f}, {100*hi:.1f}]}}"


def main() -> int:
    ap = argparse.ArgumentParser(); ap.add_argument("--level", type=int, default=3); a = ap.parse_args()
    numbers = {}
    rows = []
    for k in load_config("models.yaml")["models"]:
        for regime in ("cot", "direct"):
            f = RESULTS_DIR / "summary" / k / f"L{a.level}" / regime / "behavior_table.json"
            if not f.exists():
                continue
            t = json.loads(f.read_text())
            for target in ("v2", "v1"):
                inc = t.get(f"incongruent@{target}"); cong = t.get(f"congruent@{target}"); neu = t.get("neutral")
                if not inc:
                    continue
                rows.append((PRETTY.get(k, k), regime, target, pct(neu["accuracy"]), pct(cong["accuracy"]), pct(inc["accuracy"]),
                             pct(inc["lure_rate"]), pct(t.get(f"interference@{target}")), pct(t.get(f"facilitation@{target}"))))
                tag = f"{k.replace('-', '')}{regime}{target}"
                numbers[f"interference{tag}"] = f"{100*t[f'interference@{target}'][0]:.1f}"
                numbers[f"lurerate{tag}"] = f"{100*inc['lure_rate'][0]:.1f}"
    (PAPER / "tables").mkdir(exist_ok=True)
    with (PAPER / "tables" / "behavior.tex").open("w") as f:
        f.write("\\begin{tabular}{llcrrrrrr}\n\\toprule\nModel & Regime & Target & Neutral & Congr. & Incongr. & Lure rate & Interf. & Facil. \\\\\n\\midrule\n")
        for r in rows:
            f.write(" & ".join(str(x) for x in r) + " \\\\\n")
        f.write("\\bottomrule\n\\end{tabular}\n")
    with (PAPER / "numbers.tex").open("w") as f:
        f.write("% generated by scripts/51_tables.py -- do not edit\n")
        for key, val in sorted(numbers.items()):
            f.write(f"\\expandafter\\newcommand\\csname NUMval@{key}\\endcsname{{{val}}}\n")
        f.write("\\renewcommand{\\NUM}[1]{\\ifcsname NUMval@#1\\endcsname\\csname NUMval@#1\\endcsname\\else\\textcolor{red}{$\\langle\\langle$\\texttt{#1}$\\rangle\\rangle$}\\fi}\n")
    print(f"wrote {len(rows)} table rows, {len(numbers)} numbers")
    return 0


if __name__ == "__main__":
    sys.exit(main())
