#!/usr/bin/env python
"""Every generated figure at full size, one per page, in an appendix that does not count against
the page limit. Wide figures are rotated a quarter turn so they fill the page height instead of
being squeezed into a column.

    python scripts/66_figure_dump.py

Writes paper/tables/figure_dump.tex, which main.tex \\input{}s after the appendix sections.
"""
from __future__ import annotations

import sys
from pathlib import Path

from pypdf import PdfReader

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from cueconf.config import PROJECT_ROOT  # noqa: E402

PAPER = PROJECT_ROOT / "paper"

# name -> caption. Anything on disk but not listed is dumped last with a generic caption.
CAPTIONS = {
    "fig1_master_L3": "Figure~1 at full size.",
    "fig2_tokens_llama32-3b_L3_cot_v2": "Figure~2 at full size: per-token probes, chain-of-thought regime, "
        "intermediate variable.",
    "fig2_tokens_llama32-3b_L3_cot_v1": "Per-token probes, chain-of-thought regime, queried variable.",
    "fig2_tokens_llama32-3b_L3_direct_v2": "Per-token probes, direct regime, intermediate variable.",
    "fig4_errors_llama32-3b_L3_cot_v1": "Probing accuracy split by whether the model answers the problem "
        "correctly on its own, with the layer sweep for each half.",
    "fig5_kudo3_llama32-3b_L3_cot_v1_lureerr_i0": "Top-1 probe prediction at every layer and token, on a problem "
        "answered with the lure. Layout after \\citeauthor{kudo2026faithful}'s Figure~3.",
    "fig5_kudo3_llama32-3b_L3_cot_v1_lureerr_i1": "A second problem answered with the lure.",
    "fig5_kudo3_llama32-3b_L3_cot_v1_lureerr_i2": "A third problem answered with the lure.",
    "fig5_kudo3_llama32-3b_L3_cot_v1_err_i0": "As above, on a problem answered wrongly for another reason.",
    "fig5_kudo3_llama32-3b_L3_cot_v1_err_i1": "A second such problem.",
    "fig5_kudo3_llama32-3b_L3_cot_v2_err_i0": "As above, for the intermediate variable.",
    "fig5_kudo3_llama32-3b_L3_cot_v2_err_i1": "A second problem, intermediate variable.",
    "kudo_fig2_llama32-3b_L3_cot_v2": "Accuracy heatmaps by token and layer for the neutral, congruent and "
        "incongruent conditions, in the layout of \\citeauthor{kudo2026faithful}'s Figure~2.",
    "kudo_fig2_llama32-3b_L3_direct_v2": "The same heatmaps in the direct regime.",
    "kudo_fig5_llama32-3b_L3_cot_v2": "Span-by-layer-window patching grids, three sources, "
        "after \\citeauthor{kudo2026faithful}'s Figures~5--6.",
    "kudo_fig5_llama32-3b_L3_direct_v2": "The same grids in the direct regime.",
    "fig3_patching_llama32-3b_L3_v2": "Lure errors removed by patching, by layer, with both controls.",
}
SKIP = ("fig2_margin", "kudo_fig3_")          # superseded by fig4/fig5


def main() -> int:
    figs = sorted(p.stem for p in (PAPER / "figures").glob("*.pdf"))
    figs = [f for f in figs if not any(f.startswith(s) for s in SKIP)]
    ordered = [f for f in CAPTIONS if f in figs] + [f for f in figs if f not in CAPTIONS]
    out = ["% generated by scripts/66_figure_dump.py",
           "\\clearpage", "\\onecolumn", "\\section{Every figure at full size}",
           "Each figure below is reproduced on its own page. Wide figures are placed on landscape pages, "
           "which a PDF viewer displays upright, so nothing has to be read sideways.", ""]
    for stem in ordered:
        w, h = (float(v) / 72 for v in (lambda b: (b.width, b.height))(
            PdfReader(str(PAPER / "figures" / f"{stem}.pdf")).pages[0].mediabox))
        cap = CAPTIONS.get(stem, f"\\texttt{{{stem.replace('_', chr(92) + '_')}}}.")
        # a wide figure goes on a LANDSCAPE PAGE (pdflscape sets the page's /Rotate, so a viewer
        # shows it upright); the figure itself is never rotated. Inside `landscape`, \linewidth is
        # the long side of the page.
        wide = w / h > 1.15
        box = "width=\\linewidth,height=0.88\\textheight,keepaspectratio"
        if wide:
            out += ["\\begin{landscape}", "\\begin{figure}[p]\\centering",
                    f"\\includegraphics[{box}]{{figures/{stem}.pdf}}",
                    f"\\caption{{{cap}}}\\label{{fig:dump-{stem.replace('_', '-')}}}",
                    "\\end{figure}", "\\end{landscape}", ""]
        else:
            out += ["\\begin{figure}[p]\\centering",
                    f"\\includegraphics[{box}]{{figures/{stem}.pdf}}",
                    f"\\caption{{{cap}}}\\label{{fig:dump-{stem.replace('_', '-')}}}",
                    "\\end{figure}", "\\clearpage", ""]
    (PAPER / "tables" / "figure_dump.tex").write_text("\n".join(out))
    print(f"wrote figure_dump.tex with {len(ordered)} figures "
          f"({sum(1 for f in ordered if f in CAPTIONS)} captioned)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
