#!/usr/bin/env python
"""Render the explicit submission selection of supporting figures (CPU only).

Historical figures remain in paper/figures; new files never enter the paper automatically.
"""
from pathlib import Path

PAPER = Path(__file__).resolve().parents[1] / "paper"
FIGURES = [
    ("fig2_tokens_llama32-3b_L3_cot_v2", "fig:heat", True,
     "Llama-3.2-3B intermediate-value readouts under supplied correct calculations. "
     "Rates pool problems; tokens illustrate one example."),
    ("kudo_fig5_llama32-3b_L3_direct_v1", "fig:grid", True,
     "Llama-3.2-3B answer-only patches in four-layer windows. "
     "Bottom: maximum over windows."),
]


def main():
    lines = ["% Generated by scripts/66_figure_dump.py: explicit submission selection."]
    for stem, label, wide, caption in FIGURES:
        if not (PAPER / "figures" / f"{stem}.pdf").exists():
            raise FileNotFoundError(f"Missing selected figure: {stem}")
        env = "figure*" if wide else "figure"
        width = r"\textwidth" if wide else r"\columnwidth"
        lines.extend([rf"\begin{{{env}}}[t]", r"\centering",
                      rf"\includegraphics[width={width}]{{figures/{stem}.pdf}}",
                      rf"\caption{{{caption}}}\label{{{label}}}", rf"\end{{{env}}}", ""])
    (PAPER / "tables" / "figure_dump.tex").write_text("\n".join(lines))
    print(f"Selected {len(FIGURES)} supporting figures for the submission appendix")


if __name__ == "__main__":
    main()
