#!/usr/bin/env python
"""Render the completed paired analysis and, when available, response controls."""
from pathlib import Path
import json

ROOT=Path(__file__).resolve().parents[1]
LABEL={'llama32-3b':'Llama-3.2-3B','llama31-8b':'Llama-3.1-8B',
       'llama32-3b-it':'Llama-3.2-3B-I','llama31-8b-it':'Llama-3.1-8B-I',
       'gemma3-4b-it':'Gemma-3-4B-I','gemma3-12b-it':'Gemma-3-12B-I',
       'olmo2-1b-it':'OLMo-2-1B-I','olmo2-7b-it':'OLMo-2-7B-I',
       'llama31-8b-it-ft':'Llama-8B single-task',
       'llama31-8b-it-ftmulti':'Llama-8B multi-task',
       'llama31-8b-it-merged':'Llama-8B merged',
       'nemotron-nano-8b':'Nemotron-Nano-8B','gemma3-4b':'Gemma-3-4B'}


def load():
    path=ROOT/'results/summary/round7_paired_prompting.json'
    if not path.exists():return None
    data=json.loads(path.read_text())
    if not data['validated']:raise ValueError('unvalidated paired effects')
    return data


def narrative_numbers():
    data=load()
    if data is None:return {}
    out={f'r7-paired-{key.replace("_", "-")}':str(value) for key,value in data['counts'].items()}
    for model,tag in (('llama32-3b','l3b'),('llama31-8b','l8b')):
        ci=data['cells'][f'L3/{model}/v1']['changes_ci95']['excess']
        for suffix,value in zip(('mean','lo','hi'),ci):
            out[f'r7-paired-{tag}-{suffix}']=f'{100*value:+.2f}'
    return out


def main():
    data=load()
    if data is None:return
    lines=['% Generated by scripts/88_round7_tables.py from validated paired outputs.',
           r'\section{Paired change from answer-only to written calculations}',
           r'\label{app:round7-paired}',
           'We compare prompting conditions on exactly the same matched sets and demonstration seeds used in the 44 name-error equivalence cells. Each observation subtracts the ordinary-name rate from the misleading-name rate, then subtracts the answer-only contrast from the CoT contrast. Negative changes indicate fewer added name-suggested answers. We bootstrap matched sets, keeping all three demonstration repeats together (4,000 draws). Reliable reductions require a negative change in every demonstration set and a 95\\% interval below zero. The panel is descriptive across related checkpoints; its cells are not independent model replications.',
           'Of the 44 paired changes, '+str(data['counts']['reliable_reductions'])+' meet that rule; '+str(data['counts']['negative_change_intervals'])+' have intervals below zero. A sensitivity bootstrap that also clusters repeated arithmetic computations yields '+str(data['counts']['canonical_reliable_reductions'])+' reliable reductions. Intervals are pointwise; the count is not a multiplicity-corrected family-wide test. Before writing calculations, '+str(data['counts']['direct_equivalent'])+' cells already meet the two-point equivalence bound, compared with '+str(data['counts']['cot_equivalent'])+' afterward. Thus the equivalence count is not a count of significant improvements. Accuracy gains accompany many reductions and do not identify an effect independent of arithmetic competence.',
           r'\newsavebox{\roundsevenbox}']
    items=list(data['cells'].items())
    for part in range(0,len(items),22):
        lines += [r'\begin{table*}[t]',r'\centering\small',
                  r'\sbox{\roundsevenbox}{\begin{tabular}{@{}llrrrr@{}}',r'\toprule',
                  r'Model & Level/role & Answer-only & CoT & Paired change [95\% interval] & Accuracy gain \\',r'\midrule']
        for key,cell in items[part:part+22]:
            level,model,role=key.split('/')
            ci=cell['changes_ci95']['excess']
            change=f'{100*ci[0]:+.2f} [{100*ci[1]:+.2f}, {100*ci[2]:+.2f}]'+(r'$^{*}$' if cell['reliable_reduction'] else '')
            gain=cell['changes_ci95']['neutral_accuracy'][0]
            lines.append(' & '.join([LABEL.get(model,model),f'{level}/{role}',f"{100*cell['direct_excess']:+.2f}",
                         f"{100*cell['cot_excess']:+.2f}",change,f'{100*gain:+.1f}'])+r' \\')
        lines += [r'\bottomrule',r'\end{tabular}}',
                  r'\ifdim\wd\roundsevenbox>\textwidth\resizebox{\textwidth}{!}{\usebox{\roundsevenbox}}\else\usebox{\roundsevenbox}\fi',
                  r'\caption{Excess name errors and paired CoT-minus-answer-only changes (percentage points). Accuracy gain is the ordinary-name accuracy change. Roles v1/v2/v3 are the first/second/third variables in the problem; the queried role is v2 at level 2 and v1 otherwise. $^{*}$Reliable reduction across all demonstration sets.}',
                  r'\label{tab:round7-paired-'+str(part//22+1)+'}',r'\end{table*}']
    (ROOT/'paper/tables/round7_paired.tex').write_text('\n'.join(lines)+'\n')


if __name__=='__main__':main()
