#!/usr/bin/env python
"""Render validated response controls; pending experiments produce no manuscript files."""
from __future__ import annotations

import csv
import json
from pathlib import Path
import runpy

ROOT = Path(__file__).resolve().parents[1]
LABEL = runpy.run_path(str(ROOT/'scripts/88_round7_tables.py'))['LABEL']
FORMAT = {'names_equations':'Equations + names', 'no_names_equations':'Equations only',
          'names_values':'Values + names', 'no_names_values':'Values only'}
FINAL = {'repeat0_named0':'No query name / digit', 'repeat0_named1':'No query name / assignment',
         'repeat1_named0':'Query name / digit', 'repeat1_named1':'Query name / assignment'}
TARGET = {'v1':'Queried', 'v2':'Intermediate'}


def load(path):
    if not path.exists():
        return None
    data = json.loads(path.read_text())
    if data.get('validated') is not True or not data.get('source_files_sha256'):
        raise ValueError('response controls lack independent validation or source hashes')
    return data


def rows(data, experiment):
    cells, contrasts = [], []
    for model, result in data['models'].items():
        for role, panel in result[experiment].items():
            common = {'model':model, 'target':role}
            for style, cell in panel['cells'].items():
                row = {**common, 'response':style, 'pairs':cell['n_pairs'],
                       'computations':cell['n_computations'],
                       'pairs_by_seed':json.dumps(cell['pairs_by_seed'],sort_keys=True)}
                row.update(cell['counts'])
                for field in ('excess', 'neutral_correct', 'misleading_correct',
                              'neutral_parsed', 'misleading_parsed'):
                    for suffix, value in zip(('mean','lo','hi'),cell[field+'_ci95']):
                        row[field+'_'+suffix] = value
                cells.append(row)
            for comparison, values in panel['comparisons'].items():
                row = {**common, 'comparison':comparison,
                       'competence_matched':values['competence_matched'],
                       'change_by_seed':json.dumps(values['change_by_seed'],sort_keys=True)}
                for field, key in (('excess_change','change_ci95'),
                                   ('neutral_accuracy_change','neutral_accuracy_change_ci90')):
                    for suffix, value in zip(('mean','lo','hi'),values[key]):
                        row[field+'_'+suffix] = value
                contrasts.append(row)
    return cells, contrasts


def interval(row, field):
    return f"{100*row[field+'_mean']:+.2f} [{100*row[field+'_lo']:+.2f}, {100*row[field+'_hi']:+.2f}]"


def table(header, body, caption, label, widths):
    lines = []
    for start in range(0,len(body),12):
        lines += [
        '% Generated by scripts/89_response_control_tables.py from independently validated outputs.',
        r'\begin{table*}[t]', r'\centering\small\setlength{\tabcolsep}{3pt}',
        r'\begin{tabular}{@{}'+''.join(f'p{{{width}\\textwidth}}' for width in widths)+r'@{}}', r'\toprule',
        ' & '.join(header)+r' \\', r'\midrule',
        *(' & '.join(row)+r' \\' for row in body[start:start+12]),
        r'\bottomrule', r'\end{tabular}',
        r'\caption{'+caption+'}', r'\label{'+label+'-'+str(start//12+1)+'}', r'\end{table*}', '']
    return '\n'.join(lines)


def render(data, experiment):
    cells, contrasts = rows(data,experiment)
    labels = FORMAT if experiment=='formats' else FINAL
    cell_body = [[LABEL[row['model']],TARGET[row['target']],labels[row['response']],
                  str(row['pairs']), f"{100*row['neutral_correct_mean']:.1f}/{100*row['misleading_correct_mean']:.1f}",
                  interval(row,'excess'),
                  f"{100*row['neutral_parsed_mean']:.1f}/{100*row['misleading_parsed_mean']:.1f}"]
                 for row in cells]
    caption = ('Correct answers and parse coverage: ordinary/misleading names (percent). '
               '$N$: paired runs. Added errors: misleading-minus-ordinary rate of the name-suggested digit '
               '(percentage points, pointwise 95\\% interval). Parse failures remain in denominators. ')
    if experiment=='final_query':
        caption += 'Calculations are fixed and correct; assignments start with the queried name and equals sign.'
    cell_tex = table(['Model','Target','Response',r'$N$','Correct (O/M)',
                      'Added errors [95\\% interval]','Parsed (O/M)'],
                     cell_body,caption,'tab:r7-'+experiment+'-cells',
                     (.14,.09,.2,.045,.105,.225,.11))
    contrast_body = []
    for row in contrasts:
        a,b = row['comparison'].split(' minus ')
        contrast_body.append([LABEL[row['model']],TARGET[row['target']],labels[a]+r' $-$ '+labels[b],
                              interval(row,'excess_change'),interval(row,'neutral_accuracy_change'),
                              'Yes' if row['competence_matched'] else 'No'])
    contrast_tex = table(['Model','Target','Comparison','Error change [95\\%]',
                          'Accuracy change [90\\%]','Matched'],contrast_body,
                         'Paired changes (percentage points). Negative error changes favor the first response. '
                         'Matched: both ordinary-name accuracies reach 90\\% and their paired accuracy-change '
                         'interval lies within $\\pm2$ points. Intervals are exploratory and pointwise.',
                         'tab:r7-'+experiment+'-contrasts',(.135,.085,.28,.19,.19,.05))
    return cells, contrasts, cell_tex, contrast_tex


def main():
    data = load(ROOT/'results/summary/round7_response_controls.json')
    if data is None:
        print('Response controls are pending; no tables written.')
        return
    for experiment in ('formats','final_query'):
        cells, contrasts, cell_tex, contrast_tex = render(data,experiment)
        for kind, records in (('cells',cells),('contrasts',contrasts)):
            path = ROOT/'results/summary'/f'round7_{experiment}_{kind}.csv'
            with path.open('w',newline='') as output:
                writer = csv.DictWriter(output,fieldnames=list(records[0]))
                writer.writeheader()
                writer.writerows(records)
        for kind, content in (('cells',cell_tex),('contrasts',contrast_tex)):
            (ROOT/'paper/tables'/f'round7_{experiment}_{kind}.tex').write_text(content)
    print('Wrote response-control CSV summaries and optional appendix tables.')


if __name__=='__main__':
    main()
